### ISSUE TITLE
[Dica] SVG ao invés de PNG

### ISSUE THREAD

**Issue by p-lacerda** [liafarias/codificador-decodificar#1]
https://github.com/liafarias/codificador-decodificar/blob/746e73a71b4e2ae9377970cc3ea4a63cf45a2917/index.html#L15

Olá Lia, tudo bom contigo? Faço parte do curso da Alura Oracle One também e se permite queria fazer um comentário.
No Figma tem a opção de exportar como SVG, eu recomendaria você a fazer isso pois ao você usar o SVG, a imagem não vai ficar com qualidade ruim se for pra alguma tela com resolução maior ou menor. Parabéns pelo projeto!

**Comment by liafarias** [comment]
Obrigada pela dica, vou alterar aqui!
